
version: 0.1
phases:
  install:
    commands:
      - pip install flask
      - pip install flask-ask
      - aws cloudformation package --template-file samTemplate.yaml arn:aws:s3:::ws.chavez.improvwithalexa
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml

